# Generated by Django 4.2.3 on 2023-07-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_piclike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
