# Generated by Django 4.2.3 on 2023-07-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_picture_likes_alter_picture_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('numbers', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='kind',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kind'),
        ),
        migrations.AddField(
            model_name='picture',
            name='kind',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kind'),
        ),
    ]
