# Generated by Django 4.2.3 on 2023-07-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_kind_like_kind_picture_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='kind',
        ),
    ]
